apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mongos-0
  labels:
    name: mongos-0
    tier: database
    type: mongodb
spec:
  ports:
  - port: 27020
    name: mongos-0
  clusterIP: None
  # type: NodePort
  selector:
    # tier: database
    name: mongos-0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongos-0
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: mongos-0
      labels:
        name: mongos-0
        tier: database
    spec:
      containers:
      - name: mongo
        image: gcr.io/b-eee-technology/mongodb:3.4.0
        command:
          - mongos
          - "--configdb"
          - "config-0/config-0:27019"
          - "--transitionToAuth"
          - "--keyFile"
          - /secret/mongodb-keyfile
          - "--port"
          - "27017"
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          hostPort: 27020
          name: mongo
        resources:
          requests:
            cpu: "0.1m"
            memory: "8Mi"
          limits:
            cpu: "1"
            memory: "350Mi"
