---
apiVersion: v1
kind: Service
metadata:
  name: a-mongo-1
  labels:
    app: a-mongo-1
spec:
  ports:
  - port: 27019
    name: tcp
  clusterIP: None
  selector:
    name: a-mongo-1
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: a-mongo-1
spec:
  serviceName: a-mongo-1
  replicas: 2
  template:
    metadata:
      name: a-mongo-1
      annotations:
      labels:
        name: a-mongo-1
    spec:
      containers:
      - name: a-mongo-1
        image: mongo:3.4.2
        command:
          - mongod
          - "--replSet"
          - rs1
          - "--shardsvr"
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          hostPort: 27019
          name: mongo
        securityContext:
          privileged: true
        volumeMounts:
        - name: a-mongo-1
          mountPath: /data/db
        # - name: confdir
        #   mountPath: /conf
    #  volumes:
    #  - name: a-mongo-1
  volumeClaimTemplates:
  - metadata:
      name: a-mongo-1
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

# a-mongo-1-1.a-mongo-1.default.svc.cluster.local
# a-mongo-1-0.a-mongo-1.default.svc.cluster.local