apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notificator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: beee-notificator
    spec:
      containers:
      - name: beee-notificator
        image: gcr.io/bizplatform-ix-production/beee-notificator:latest
        env:
          - name: ENV
            value: production
          - name: MESSAGING_BACKEND
            value: "nsq"
          - name: APP_MONGODB
            value: "beee-dev"
          - name: SENTRY_LOGGER
            value: "1"
          - name: SENTRY_DSN
            value: https://65605361f8b04f57aee542309cad344f:fa50858f8b72441b8f05c3dc6e28bf5e@sentry.io/160141
        ports:
        - containerPort: 8081
          hostPort: 8081
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
---
apiVersion: v1
kind: Service
metadata:
  name: beee-notificator
  labels:
    name: beee-notificator
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: beee-notificator
