apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notificator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: beee-notificator
    spec:
      containers:
      - name: beee-notificator
        image: gcr.io/bizplatform-ix-production/beee-notificator:latest
        env:
          - name: ENV
            value: dev
          - name: MESSAGING_BACKEND
            value: "nsq"
          - name: APP_MONGODB
            value: "beee-dev"
          - name: SENTRY_LOGGER
            value: "1"
          - name: SENTRY_DSN
            value: https://43810d9a2ae2450ebc2365690dfd3493:a64d9e2fd10544ecbedb85ab28723baf@sentry.io/141941
        ports:
        - containerPort: 8081
          hostPort: 8081
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
---
apiVersion: v1
kind: Service
metadata:
  name: beee-notificator
  labels:
    name: beee-notificator
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: beee-notificator
