kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: a-mongo-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "pd-ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
