apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: a-mongo-1
  labels:
    name: a-mongo-1
    tier: database
    type: mongo
spec:
  ports:
  - port: 27018
    name: mongo
  # type: NodePort
  clusterIP: None
  selector:
    tier: database
    name: a-mongo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: a-mongo-1
  annotations:
    volume.beta.kubernetes.io/storage-class: "pd-ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a-mongo-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: a-mongo-1
    spec:
      volumes:
        - name: a-mongo-1
          persistentVolumeClaim:
            claimName: a-mongo-1
      containers:
      - name: mongo
        image: mongo:3.3.10
        command:
          - mongod
          - "--replSet"
          - rs0
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          hostPort: 27018
          name: mongo
        resources:
          requests:
            cpu: "0.1m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "350Mi"
        volumeMounts:
        -  mountPath: /data/db
           name: a-mongo-1