# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
#   name: a-minio-1
#   labels:
#     name: a-minio-1
#     tier: minio
#     type: minio
# spec:
#   ports:
#   - port: 80
#     targetPort: 9000
#     name: http
#   - port: 9000
#     targetPort: 9000
#     name: http2    
#   clusterIP: None
#   selector:
#     name: a-minio-1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
#   name: a-minio-1-api
#   labels:
#     name: a-minio-1-api
#     tier: minio
#     type: minio
# spec:
#   ports:
#   - port: 9000
#     targetPort: 9000
#     name: http2    
#   # clusterIP: None
#   selector:
#     name: a-minio-1
# #   # type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a-minio-1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: a-minio-1
      labels:
        name: a-minio-1
        tier: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        command:
          - minio
          - "server"
          - "/export/docker"
        env:
          # - name: minio_PASSWORD
          #   value: tHiDF3fEVU1wFnNun09i7N9usuFee8l5V6SZymFEEfI=
          - name: MINIO_ACCESS_KEY
            value: XLQHM7X3GWE4IAAV5D27
          - name: MINIO_SECRET_KEY
            value: wvR+yahN/aMr5epi69enpNaRSgOWBTs5n56t7szY
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          hostPort: 9000
        resources:
          requests:
            cpu: "0.1m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "350Mi"
