apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: a-mongo-2
  labels:
    name: a-mongo-2
    tier: database
    type: mongodb
spec:
  ports:
  - port: 27018
    name: a-mongo-2
  clusterIP: None
  # type: NodePort
  selector:
    # tier: database
    name: a-mongo-2
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: a-mongo-2-pd-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: asia-east1-a
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: a-mongo-2
  annotations:
    volume.beta.kubernetes.io/storage-class: "a-mongo-2-pd-ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a-mongo-2
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: a-mongo-2
      labels:
        name: a-mongo-2
        tier: database
    spec:
      volumes:
        - name: a-mongo-2
          persistentVolumeClaim:
            claimName: a-mongo-2
      containers:
      - name: mongo
        image: mongo:3.4.2
        command:
          - mongod
          - "--replSet"
          - rs0
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          hostPort: 27018
          name: mongo
        resources:
          requests:
            cpu: "0.1m"
            memory: "16Mi"
          limits:
            cpu: "1"
        volumeMounts:
        -  mountPath: /data/db
           name: a-mongo-2