apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linker-prod
  # annotations:
  #   nginx.org/ssl-services: "b-eee-lp-s"
spec:
  tls:
  - hosts:
    - linker-app.com
    secretName: linker-secret
  rules:
  - host: linker-app.com
    http:
      paths:
      - backend:
          serviceName: b-eee-lp-s
          servicePort: 80
  - host: www.linker-app.com
    http:
      paths:
      - backend:
          serviceName: beee-ui
          servicePort: 80