apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linker-prod-nossl
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.org/client-max-body-size: "1024m"
spec:
  rules:
  # - host: stg-minio.b-eee.io
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: a-minio-1
  #         servicePort: 80
  #     - backend:
  #         serviceName: a-minio-1-api
  #         servicePort: 9000
  # - host: nfj.linker-app.com
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: d-neo4j-0
  #         servicePort: 80
  # - host: influx.linker-app.com
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: chronograf-0
  #         servicePort: 80
  # - host: proxy.linker-app.com
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: beee-linkerproxy
  #         servicePort: 80          
  # - host: neo4j-backup
  #   http:
  #     paths:
  #     - backend:
  #         serviceName: d-neo4j-0
  #         servicePort: 6362
  - host: admin.linker-app.com
    http:
      paths:
      - backend:
          serviceName: beee-admintool
          servicePort: 80
  