apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linker-prod
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.org/client-max-body-size: "1024m"
spec:
  tls:
  - hosts:
    - stg-www.b-eee.io
    secretName: linker-secret
  - hosts:
    - stg.b-eee.io
    secretName: linker-secret
  # - secretName: linker-secret
  #   hosts:
  #   - stg-www.b-eee.io
  #   - stg.b-eee.io
  rules:
  - host: stg-www.b-eee.io
    http:
      paths:
      - backend:
          serviceName: b-eee-lp
          servicePort: 80
  - host: stg.b-eee.io
    http:
      paths:
      - backend:
          serviceName: beee-ui
          servicePort: 80
  - host: stg-nfj.b-eee.io
    http:
      paths:
      - backend:
          serviceName: d-neo4j-0
          servicePort: 80