apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linker-prod
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: linker-secret  
    hosts:
    - stg-www.b-eee.io
    - stg.b-eee.io
  rules:
  - host: stg-www.b-eee.io
    http:
      paths:
      - backend:
          serviceName: b-eee-lp
          servicePort: 80  
  - host: stg.b-eee.io
    http:
      paths:
      - backend:
          serviceName: beee-ui
          servicePort: 80