apiVersion: v1
kind: Service
metadata:
  name: linker-stg-nodeport-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 3306
    name: tcp-mysql
  - port: 27018
    name: tcp-mongodb
  - port: 4150
    targetPort: 4150
    name: tcp-nsq0
  - port: 4151
    name: tcp-nsq1
  - port: 4161
    name: tcp-nsq2
  - port: 4171
    name: tcp-nsq3
  - port: 9000
    targetPort: 9000
    name: minio
  - port: 7474
    targetPort: 7474
    name: a-neo4j-0
  - port: 6362
    targetPort: 6362
    name: d-neo4j-0-backup
  - port: 4002
    targetPort: 4002
    name: linker-proxy
  selector:
    app: nginx-ingress-controller

    # update tblcandidates set Votes = '" &updatedVotes "' where Name like '%Mark Aljer%'