apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: user-metrics
spec:
  template:
    metadata:
      labels:
        app: user-metrics
      name: user-metrics
    spec:
      containers:
      - image: gcr.io/b-eee-technology/user-metrics:latest
        imagePullPolicy: Always
        name: user-metrics
        ports:
          - containerPort: 8125
            name: user-metrics
        env:
          - name: API_KEY
            value: 89f8627f52dd67c483a94ccc78dfa3a6
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups